[package]
name = "Advent-of-Code"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "2015_01"
path = "2015/Rust/01.rs"

[[bin]]
name = "2016_01"
path = "2016/Rust/01.rs"

# [[bin]]
# name = "2015_02"
# path = "2015/Rust/02.rs"
