[package]
name = "Advent-of-Code"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "2015"
path = "2015/Rust/main.rs"

[[bin]]
name = "2016"
path = "2016/Rust/main.rs"

[[bin]]
name = "2017"
path = "2017/Rust/main.rs"

[[bin]]
name = "2018"
path = "2018/Rust/main.rs"
